# Generated by Django 5.0.6 on 2024-06-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Client',
        ),
    ]
